package com.zimuzeng.outfitapp.garment.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.openai.client.OpenAIClient;
import com.openai.models.ResponseFormatJsonObject;
import com.openai.models.chat.completions.ChatCompletion;
import com.openai.models.chat.completions.ChatCompletionContentPart;
import com.openai.models.chat.completions.ChatCompletionContentPartImage;
import com.openai.models.chat.completions.ChatCompletionContentPartText;
import com.openai.models.chat.completions.ChatCompletionCreateParams;
import com.zimuzeng.outfitapp.common.exception.AppException;
import com.zimuzeng.outfitapp.common.exception.ErrorCode;
import com.zimuzeng.outfitapp.config.QwenProperties;
import com.zimuzeng.outfitapp.garment.model.ExtractedGarmentMetadata;
import com.zimuzeng.outfitapp.garment.model.Fit;
import com.zimuzeng.outfitapp.garment.model.GarmentCategory;
import com.zimuzeng.outfitapp.garment.model.GarmentLength;
import com.zimuzeng.outfitapp.garment.model.GarmentPattern;
import com.zimuzeng.outfitapp.garment.model.Material;
import com.zimuzeng.outfitapp.garment.model.Neckline;
import com.zimuzeng.outfitapp.garment.model.Occasion;
import com.zimuzeng.outfitapp.garment.model.Season;
import com.zimuzeng.outfitapp.garment.model.Silhouette;
import com.zimuzeng.outfitapp.garment.model.SleeveLength;
import com.zimuzeng.outfitapp.garment.model.Warmth;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/**
 * Qwen counterpart to {@link GeminiGarmentMetadataAnalyzer}: sends a single garment crop to Qwen
 * (via DashScope's OpenAI-compatible API - see {@link com.zimuzeng.outfitapp.config.QwenConfig})
 * and asks it to extract the same structured fashion metadata.
 *
 * <p>Unlike Gemini's {@code responseSchema}, Qwen's JSON mode ({@code response_format:
 * json_object}) only guarantees syntactically valid JSON, not conformance to a particular shape -
 * so every field name, type, and the full set of allowed enum values is spelled out in the
 * system instruction instead of a typed schema. The enum options are generated by reflecting over
 * the same enum classes {@link GeminiGarmentMetadataAnalyzer} uses, so the two prompts can't drift
 * out of sync with each other.
 *
 * <p>Active when {@code garment.analysis-provider} is {@code qwen} - see
 * {@link GeminiGarmentMetadataAnalyzer} for the default implementation of
 * {@link GarmentMetadataAnalyzer}.
 *
 * <p>Because {@code json_object} mode does not enforce enum membership, unrecognized enum
 * strings fall back to {@code OTHER} (or are dropped from multi-value lists) rather than
 * failing the whole metadata extraction.
 */
@Component
@ConditionalOnProperty(name = "garment.analysis-provider", havingValue = "qwen")
@RequiredArgsConstructor
@Slf4j
public class QwenGarmentMetadataAnalyzer implements GarmentMetadataAnalyzer {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    private static final String SYSTEM_INSTRUCTION = """
            You are a fashion assistant analyzing a single cropped photo of one garment or
            accessory. Extract structured metadata describing exactly what is visible. Pick the
            single best-fitting value for enum fields, and use the "NOT_APPLICABLE" option for
            any field that genuinely does not apply to this kind of item (for example sleeve
            length or neckline on a pair of shoes or a bag). Only report secondary colours that
            are clearly present in addition to the primary colour - leave the list empty if there
            is only one colour. Style tags should be short, lowercase aesthetic/style labels
            (e.g. "minimalist", "korean", "quiet luxury", "streetwear") and can be an empty list
            if none clearly apply.

            Respond with ONLY a JSON object of this exact shape, and nothing else - every field
            is required, and enum fields must be set to exactly one of their listed values:
            {
              "category": one of %s,
              "subcategory": "<short free-text string>",
              "primaryColour": "<free-text string>",
              "secondaryColours": ["<free-text string>", ...],
              "pattern": one of %s,
              "seasons": [zero or more of %s],
              "occasions": [zero or more of %s],
              "fit": one of %s,
              "silhouette": one of %s,
              "material": one of %s,
              "sleeveLength": one of %s,
              "neckline": one of %s,
              "length": one of %s,
              "warmth": one of %s,
              "formality": <integer from 1 to 5>,
              "styleTags": ["<lowercase string>", ...]
            }
            """
            .formatted(
                    enumOptions(GarmentCategory.class),
                    enumOptions(GarmentPattern.class),
                    enumOptions(Season.class),
                    enumOptions(Occasion.class),
                    enumOptions(Fit.class),
                    enumOptions(Silhouette.class),
                    enumOptions(Material.class),
                    enumOptions(SleeveLength.class),
                    enumOptions(Neckline.class),
                    enumOptions(GarmentLength.class),
                    enumOptions(Warmth.class));

    private static final String PROMPT_TEMPLATE = "Analyze this garment crop and extract its metadata. "
            + "It was detected and labeled \"%s\" by an earlier detection pass.";

    private final OpenAIClient qwenClient;
    private final QwenProperties qwenProperties;

    @Override
    public String modelName() {
        return qwenProperties.model();
    }

    @Override
    public ExtractedGarmentMetadata analyze(byte[] cropBytes, String contentType, String label) {
        ChatCompletionCreateParams params = ChatCompletionCreateParams.builder()
                .model(qwenProperties.model())
                .addSystemMessage(SYSTEM_INSTRUCTION)
                .addUserMessageOfArrayOfContentParts(List.of(
                        imagePart(cropBytes, contentType), textPart(PROMPT_TEMPLATE.formatted(label))))
                .responseFormat(ResponseFormatJsonObject.builder().build())
                .build();

        long startedAt = System.currentTimeMillis();
        ChatCompletion completion = qwenClient.chat().completions().create(params);
        log.info("Qwen model {} metadata extraction call completed in {} ms (label=\"{}\")",
                qwenProperties.model(), System.currentTimeMillis() - startedAt, label);

        return parse(content(completion));
    }

    private ChatCompletionContentPart imagePart(byte[] imageBytes, String contentType) {
        String dataUrl = "data:" + contentType + ";base64," + Base64.getEncoder().encodeToString(imageBytes);
        return ChatCompletionContentPart.ofImageUrl(ChatCompletionContentPartImage.builder()
                .imageUrl(ChatCompletionContentPartImage.ImageUrl.builder().url(dataUrl).build())
                .build());
    }

    private ChatCompletionContentPart textPart(String text) {
        return ChatCompletionContentPart.ofText(ChatCompletionContentPartText.builder().text(text).build());
    }

    private String content(ChatCompletion completion) {
        return completion.choices().get(0).message().content()
                .orElseThrow(() -> new AppException(ErrorCode.QWEN_RESPONSE_PARSE_ERROR, "empty response content"));
    }

    private ExtractedGarmentMetadata parse(String json) {
        try {
            RawMetadata raw = OBJECT_MAPPER.readValue(json, RawMetadata.class);
            return toExtractedMetadata(raw);
        } catch (JsonProcessingException ex) {
            log.error("Failed to parse Qwen garment metadata response: {}", json, ex);
            throw new AppException(ErrorCode.QWEN_RESPONSE_PARSE_ERROR, ex, ex.getMessage());
        }
    }

    private ExtractedGarmentMetadata toExtractedMetadata(RawMetadata raw) {
        return new ExtractedGarmentMetadata(
                parseEnum(GarmentCategory.class, raw.category(), GarmentCategory.OTHER),
                blankToEmpty(raw.subcategory()),
                blankToEmpty(raw.primaryColour()),
                raw.secondaryColours() == null ? List.of() : raw.secondaryColours(),
                parseEnum(GarmentPattern.class, raw.pattern(), GarmentPattern.OTHER),
                parseEnumList(Season.class, raw.seasons()),
                parseEnumList(Occasion.class, raw.occasions()),
                parseEnum(Fit.class, raw.fit(), Fit.OTHER),
                parseEnum(Silhouette.class, raw.silhouette(), Silhouette.OTHER),
                parseEnum(Material.class, raw.material(), Material.OTHER),
                parseEnum(SleeveLength.class, raw.sleeveLength(), SleeveLength.OTHER),
                parseEnum(Neckline.class, raw.neckline(), Neckline.OTHER),
                parseEnum(GarmentLength.class, raw.length(), GarmentLength.OTHER),
                parseEnum(Warmth.class, raw.warmth(), Warmth.OTHER),
                clampFormality(raw.formality()),
                raw.styleTags() == null ? List.of() : raw.styleTags());
    }

    private <E extends Enum<E>> E parseEnum(Class<E> type, String raw, E fallback) {
        String normalized = normalizeEnumName(raw);
        if (normalized == null) {
            log.warn("Missing Qwen {} value, falling back to {}", type.getSimpleName(), fallback);
            return fallback;
        }
        try {
            return Enum.valueOf(type, normalized);
        } catch (IllegalArgumentException ex) {
            log.warn("Unknown Qwen {} value '{}', falling back to {}", type.getSimpleName(), raw, fallback);
            return fallback;
        }
    }

    private <E extends Enum<E>> List<E> parseEnumList(Class<E> type, List<String> raw) {
        if (raw == null || raw.isEmpty()) {
            return List.of();
        }
        List<E> parsed = new ArrayList<>();
        for (String value : raw) {
            String normalized = normalizeEnumName(value);
            if (normalized == null) {
                continue;
            }
            try {
                parsed.add(Enum.valueOf(type, normalized));
            } catch (IllegalArgumentException ex) {
                log.warn("Dropping unknown Qwen {} value '{}'", type.getSimpleName(), value);
            }
        }
        return parsed;
    }

    private static String normalizeEnumName(String raw) {
        if (raw == null || raw.isBlank()) {
            return null;
        }
        return raw.trim().toUpperCase(Locale.ROOT).replace('-', '_').replace(' ', '_');
    }

    private static String blankToEmpty(String value) {
        return value == null ? "" : value;
    }

    private static int clampFormality(int formality) {
        return Math.max(1, Math.min(5, formality));
    }

    private static String enumOptions(Class<? extends Enum<?>> enumType) {
        return List.of(enumType.getEnumConstants()).stream()
                .map(Enum::name)
                .collect(Collectors.joining(", ", "[", "]"));
    }

    /**
     * Raw shape of the Qwen JSON response, with enum fields kept as strings until validated
     * against the actual Java enums in {@link #toExtractedMetadata(RawMetadata)}.
     */
    private record RawMetadata(
            String category,
            String subcategory,
            String primaryColour,
            List<String> secondaryColours,
            String pattern,
            List<String> seasons,
            List<String> occasions,
            String fit,
            String silhouette,
            String material,
            String sleeveLength,
            String neckline,
            String length,
            String warmth,
            int formality,
            List<String> styleTags) {
    }
}
