package com.zimuzeng.outfitapp.garment.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.openai.client.OpenAIClient;
import com.openai.models.ResponseFormatJsonObject;
import com.openai.models.chat.completions.ChatCompletion;
import com.openai.models.chat.completions.ChatCompletionContentPart;
import com.openai.models.chat.completions.ChatCompletionContentPartImage;
import com.openai.models.chat.completions.ChatCompletionContentPartText;
import com.openai.models.chat.completions.ChatCompletionCreateParams;
import com.zimuzeng.outfitapp.common.exception.AppException;
import com.zimuzeng.outfitapp.common.exception.ErrorCode;
import com.zimuzeng.outfitapp.common.text.UserFacingCopyStyle;
import com.zimuzeng.outfitapp.config.QwenProperties;
import com.zimuzeng.outfitapp.config.QwenRequestOptions;
import com.zimuzeng.outfitapp.garment.model.Colour;
import com.zimuzeng.outfitapp.garment.model.ExtractedGarmentMetadata;
import com.zimuzeng.outfitapp.garment.model.Fit;
import com.zimuzeng.outfitapp.garment.model.GarmentCategory;
import com.zimuzeng.outfitapp.garment.model.GarmentGroup;
import com.zimuzeng.outfitapp.garment.model.GarmentLength;
import com.zimuzeng.outfitapp.garment.model.GarmentPattern;
import com.zimuzeng.outfitapp.garment.model.LayerRole;
import com.zimuzeng.outfitapp.garment.model.Material;
import com.zimuzeng.outfitapp.garment.model.Neckline;
import com.zimuzeng.outfitapp.garment.model.Occasion;
import com.zimuzeng.outfitapp.garment.model.Season;
import com.zimuzeng.outfitapp.garment.model.Silhouette;
import com.zimuzeng.outfitapp.garment.model.SleeveLength;
import com.zimuzeng.outfitapp.garment.model.StyleTag;
import com.zimuzeng.outfitapp.garment.model.Warmth;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * Sends a single garment crop to Qwen (via DashScope's OpenAI-compatible API - see
 * {@link com.zimuzeng.outfitapp.config.QwenConfig}) and asks it to extract structured fashion
 * metadata plus a plain-language visual description.
 *
 * <p>Qwen's JSON mode ({@code response_format: json_object}) only guarantees syntactically valid
 * JSON, not conformance to a particular shape - so every field name, type, and the full set of
 * allowed enum values is spelled out in the system instruction instead of a typed schema. The
 * enum options are generated by reflecting over the Java enum classes.
 *
 * <p>Because {@code json_object} mode does not enforce enum membership, unrecognized enum
 * strings fall back to a sensible default (or are dropped from multi-value lists) rather than
 * failing the whole metadata extraction.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class QwenGarmentMetadataAnalyzer implements GarmentMetadataAnalyzer {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    private static final int MAX_STYLE_TAGS = 3;

    private static final String SYSTEM_INSTRUCTION = (
            """
            You are a fashion assistant analyzing a cropped photo of a single garment. An
            earlier detection pass labeled the subject garment; treat that labeled garment as
            the sole subject of every field you return. Extract structured metadata for that
            garment only. Ignore accessories (jewelry, belts, bags, hats, scarves, glasses,
            phones, and similar), body parts, background, and any other garments that happen
            to appear in the crop - do not describe them and do not let them influence
            category, colours, pattern, style tags, or any other field. If you are unsure
            whether a detail belongs to the labeled garment or to something else, omit it.

            Taxonomy:
            - Set garmentGroup to the outfit slot: TOP, BOTTOM, ONE_PIECE, OUTERWEAR, FOOTWEAR,
              or ACCESSORY.
            - Set category to the best matching type within that group. Use OTHER with the
              correct garmentGroup when the slot is clear but the exact type is not. Use
              OTHER_ACCESSORY only for accessories.
            - Colours must be from the controlled colour list (map "navy blue" -> NAVY, etc.).
              Only report secondaryColours clearly present in addition to primaryColour.
            - Occasions are contexts (EVERYDAY, WORK, DATE, ...) - never encode casual/formal
              as occasions; that belongs in formality (1 = very casual, 5 = very formal).
            - seasons: list applicable seasons, or leave empty for year-round / all-season.
            - warmth: LIGHT, MEDIUM, or HEAVY (use MEDIUM if unsure). Always set for clothing
              and footwear.
            - material: only visually obvious classes (DENIM, LEATHER, KNIT, WOVEN, SHEER);
              use UNKNOWN if you cannot tell.
            - layerRole: BASE/MID/OUTER for tops and outerwear; NOT_APPLICABLE otherwise.
            - length: tops/outerwear use CROPPED/REGULAR/LONGLINE; skirts/dresses use
              MINI/MIDI/MAXI; trousers/jeans/leggings use SHORT/REGULAR/LONG; else
              NOT_APPLICABLE.
            - silhouette: set a meaningful value mainly for dresses, skirts, and tailored
              pieces; otherwise NOT_APPLICABLE is fine.
            - sleeveLength / neckline / fit: use NOT_APPLICABLE when the attribute does not
              apply to this kind of item.
            - styleTags: at most 3 labels from the closed list; empty list if none fit.

            Also write a "description" about the labeled garment only.
            """
            + UserFacingCopyStyle.GARMENT_DESCRIPTION_INSTRUCTION
            + """

            Respond with ONLY a JSON object of this exact shape, and nothing else - every field
            is required, and enum fields must be set to exactly one of their listed values:
            {
              "garmentGroup": one of %s,
              "category": one of %s,
              "primaryColour": one of %s,
              "secondaryColours": [zero or more of %s],
              "pattern": one of %s,
              "seasons": [zero or more of %s],
              "occasions": [zero or more of %s],
              "fit": one of %s,
              "silhouette": one of %s,
              "material": one of %s,
              "sleeveLength": one of %s,
              "neckline": one of %s,
              "length": one of %s,
              "layerRole": one of %s,
              "warmth": one of %s,
              "formality": <integer from 1 to 5>,
              "styleTags": [zero or more of %s],
              "description": "<plain English description>"
            }
            """)
            .formatted(
                    enumOptions(GarmentGroup.class),
                    enumOptions(GarmentCategory.class),
                    enumOptions(Colour.class),
                    enumOptions(Colour.class),
                    enumOptions(GarmentPattern.class),
                    enumOptions(Season.class),
                    enumOptions(Occasion.class),
                    enumOptions(Fit.class),
                    enumOptions(Silhouette.class),
                    enumOptions(Material.class),
                    enumOptions(SleeveLength.class),
                    enumOptions(Neckline.class),
                    enumOptions(GarmentLength.class),
                    enumOptions(LayerRole.class),
                    enumOptions(Warmth.class),
                    enumOptions(StyleTag.class));

    private static final String PROMPT_TEMPLATE =
            "Analyze this garment crop and extract metadata for only the garment labeled \"%s\". "
                    + "Ignore accessories and any other items visible in the crop.";

    private final OpenAIClient qwenClient;
    private final QwenProperties qwenProperties;

    @Override
    public String modelName() {
        return qwenProperties.model();
    }

    @Override
    public ExtractedGarmentMetadata analyze(byte[] cropBytes, String contentType, String label) {
        ChatCompletionCreateParams params = QwenRequestOptions.withoutThinking(ChatCompletionCreateParams.builder()
                        .model(qwenProperties.model())
                        .addSystemMessage(SYSTEM_INSTRUCTION)
                        .addUserMessageOfArrayOfContentParts(List.of(
                                imagePart(cropBytes, contentType), textPart(PROMPT_TEMPLATE.formatted(label))))
                        .responseFormat(ResponseFormatJsonObject.builder().build()))
                .build();

        long startedAt = System.currentTimeMillis();
        ChatCompletion completion = qwenClient.chat().completions().create(params);
        log.info("Qwen model {} metadata extraction call completed in {} ms (label=\"{}\")",
                qwenProperties.model(), System.currentTimeMillis() - startedAt, label);

        return parse(content(completion));
    }

    private ChatCompletionContentPart imagePart(byte[] imageBytes, String contentType) {
        String dataUrl = "data:" + contentType + ";base64," + Base64.getEncoder().encodeToString(imageBytes);
        return ChatCompletionContentPart.ofImageUrl(ChatCompletionContentPartImage.builder()
                .imageUrl(ChatCompletionContentPartImage.ImageUrl.builder().url(dataUrl).build())
                .build());
    }

    private ChatCompletionContentPart textPart(String text) {
        return ChatCompletionContentPart.ofText(ChatCompletionContentPartText.builder().text(text).build());
    }

    private String content(ChatCompletion completion) {
        return completion.choices().get(0).message().content()
                .orElseThrow(() -> new AppException(ErrorCode.QWEN_RESPONSE_PARSE_ERROR, "empty response content"));
    }

    private ExtractedGarmentMetadata parse(String json) {
        try {
            RawMetadata raw = OBJECT_MAPPER.readValue(json, RawMetadata.class);
            return toExtractedMetadata(raw);
        } catch (JsonProcessingException ex) {
            log.error("Failed to parse Qwen garment metadata response: {}", json, ex);
            throw new AppException(ErrorCode.QWEN_RESPONSE_PARSE_ERROR, ex, ex.getMessage());
        }
    }

    private ExtractedGarmentMetadata toExtractedMetadata(RawMetadata raw) {
        List<StyleTag> styleTags = parseEnumList(StyleTag.class, raw.styleTags());
        if (styleTags.size() > MAX_STYLE_TAGS) {
            styleTags = styleTags.subList(0, MAX_STYLE_TAGS);
        }
        return new ExtractedGarmentMetadata(
                parseEnum(GarmentGroup.class, raw.garmentGroup(), GarmentGroup.TOP),
                parseEnum(GarmentCategory.class, raw.category(), GarmentCategory.OTHER),
                parseEnum(Colour.class, raw.primaryColour(), Colour.OTHER),
                parseEnumList(Colour.class, raw.secondaryColours()),
                parseEnum(GarmentPattern.class, raw.pattern(), GarmentPattern.OTHER),
                parseEnumList(Season.class, raw.seasons()),
                parseEnumList(Occasion.class, raw.occasions()),
                parseEnum(Fit.class, raw.fit(), Fit.OTHER),
                parseEnum(Silhouette.class, raw.silhouette(), Silhouette.NOT_APPLICABLE),
                parseEnum(Material.class, raw.material(), Material.UNKNOWN),
                parseEnum(SleeveLength.class, raw.sleeveLength(), SleeveLength.NOT_APPLICABLE),
                parseEnum(Neckline.class, raw.neckline(), Neckline.NOT_APPLICABLE),
                parseEnum(GarmentLength.class, raw.length(), GarmentLength.NOT_APPLICABLE),
                parseEnum(LayerRole.class, raw.layerRole(), LayerRole.NOT_APPLICABLE),
                parseEnum(Warmth.class, raw.warmth(), Warmth.MEDIUM),
                clampFormality(raw.formality()),
                styleTags,
                blankToEmpty(raw.description()));
    }

    private <E extends Enum<E>> E parseEnum(Class<E> type, String raw, E fallback) {
        String normalized = normalizeEnumName(raw);
        if (normalized == null) {
            log.warn("Missing Qwen {} value, falling back to {}", type.getSimpleName(), fallback);
            return fallback;
        }
        try {
            return Enum.valueOf(type, normalized);
        } catch (IllegalArgumentException ex) {
            log.warn("Unknown Qwen {} value '{}', falling back to {}", type.getSimpleName(), raw, fallback);
            return fallback;
        }
    }

    private <E extends Enum<E>> List<E> parseEnumList(Class<E> type, List<String> raw) {
        if (raw == null || raw.isEmpty()) {
            return List.of();
        }
        List<E> parsed = new ArrayList<>();
        for (String value : raw) {
            String normalized = normalizeEnumName(value);
            if (normalized == null) {
                continue;
            }
            try {
                parsed.add(Enum.valueOf(type, normalized));
            } catch (IllegalArgumentException ex) {
                log.warn("Dropping unknown Qwen {} value '{}'", type.getSimpleName(), value);
            }
        }
        return parsed;
    }

    private static String normalizeEnumName(String raw) {
        if (raw == null || raw.isBlank()) {
            return null;
        }
        return raw.trim().toUpperCase(Locale.ROOT).replace('-', '_').replace(' ', '_');
    }

    private static String blankToEmpty(String value) {
        return value == null ? "" : value;
    }

    private static int clampFormality(int formality) {
        return Math.max(1, Math.min(5, formality));
    }

    private static String enumOptions(Class<? extends Enum<?>> enumType) {
        return List.of(enumType.getEnumConstants()).stream()
                .map(Enum::name)
                .collect(Collectors.joining(", ", "[", "]"));
    }

    /**
     * Raw shape of the Qwen JSON response, with enum fields kept as strings until validated
     * against the actual Java enums in {@link #toExtractedMetadata(RawMetadata)}.
     */
    private record RawMetadata(
            String garmentGroup,
            String category,
            String primaryColour,
            List<String> secondaryColours,
            String pattern,
            List<String> seasons,
            List<String> occasions,
            String fit,
            String silhouette,
            String material,
            String sleeveLength,
            String neckline,
            String length,
            String layerRole,
            String warmth,
            int formality,
            List<String> styleTags,
            String description) {
    }
}
